app/styles/globals.css.ts
app/styles/theme.css.ts
package.json
pnpm-lock.yaml
vite.config.ts

closed #59 
追加で本番ビルドが壊れていたので修正しました。
https://x.com/re_taro_/status/1792935985333801130

feat: add theme.css.ts

---

app/styles/theme.css.ts

feat: add color to design token

---

.github/renovate.json
public/robots.txt

feat: add robots.txt for SEO

---

.storybook/preview-head.html
app/components/Countdown/styles.css.ts
app/components/SectionTitle/SectionTitle.tsx
app/components/SectionTitle/styles.css.ts
app/root.tsx
app/routes/_index/features/PhilosophySection/PhilosophySection.stories.ts
app/routes/_index/features/PhilosophySection/PhilosophySection.tsx
app/routes/_index/features/PhilosophySection/index.ts
app/routes/_index/features/PhilosophySection/styles.css.ts
app/routes/_index/route.tsx
app/styles/global-css.css.ts
app/styles/globals.css.ts
app/styles/layers.css.ts
app/styles/theme.css.ts
tests/top.test.ts

feat: impl philosophy section

---

app/components/Countdown/Countdown.tsx
app/routes/_index/features/TitleScrean/TitleScrean.stories.ts
app/routes/_index/features/TitleScrean/TitleScrean.tsx
app/routes/_index/features/TitleScrean/index.ts
app/routes/_index/features/TitleScrean/styles.css.ts

feat: implement top screen

---

app/components/SectionTitle/SectionTitle.stories.ts
app/components/SectionTitle/SectionTitle.tsx
app/components/SectionTitle/styles.css.ts
app/routes/_index/features/OverviewBox/OverviewBox.stories.tsx
app/routes/_index/features/OverviewBox/OverviewBox.tsx
app/routes/_index/features/OverviewBox/index.ts
app/routes/_index/features/OverviewBox/styles.css.ts
app/routes/_index/features/OverviewSection/OverviewSection.stories.ts
app/routes/_index/features/OverviewSection/OverviewSection.tsx
app/routes/_index/features/OverviewSection/index.ts
app/routes/_index/features/OverviewSection/styles.css.ts
app/routes/_index/features/PhilosophySection/styles.css.ts
app/routes/_index/route.tsx
package.json
pnpm-lock.yaml
tests/top.test.ts

feat: impl overview section

---

app/routes/_index/features/HeroSection/HeroSection.tsx

fix: hero title

---

app/routes/_index/features/PhilosophySection/styles.css.ts

fix: update padding top of each section

---

app/routes/_index/features/EventCard/EventCard.stories.ts
app/routes/_index/features/EventCard/EventCard.tsx
app/routes/_index/features/EventCard/index.ts
app/routes/_index/features/EventCard/styles.css.ts
app/routes/_index/features/OverviewSection/OverviewSection.stories.ts
app/routes/_index/features/OverviewSection/OverviewSection.tsx
app/routes/_index/features/OverviewSection/styles.css.ts

feat: impl event section to OverviewSection

---

app/features/ErrorBoundary/ErrorBoundary.stories.ts
app/features/ErrorBoundary/ErrorBoundary.tsx
app/features/ErrorBoundary/index.ts
app/features/ErrorTitle/ErrorTitle.stories.ts
app/features/ErrorTitle/ErrorTitle.tsx
app/features/ErrorTitle/index.ts
app/hooks/useScramble.ts
app/root.tsx

feat: impl ErrorBoundary

---

app/routes/events/features/GameEventCard/GameEventCard.stories.ts
app/routes/events/features/GameEventCard/GameEventCard.tsx
app/routes/events/features/GameEventCard/index.ts
app/routes/events/features/GameEventCard/styles.css.ts

feat: impl GameEventCard

---

app/routes/events/features/LiveEventCard/LiveEventCard.stories.ts
app/routes/events/features/LiveEventCard/LiveEventCard.tsx
app/routes/events/features/LiveEventCard/index.ts
app/routes/events/features/LiveEventCard/styles.css.ts
content-collections.ts

feat: impl LiveEventCard

---

.github/workflows/lighthouse.yml
app/routes/_index/route.tsx
app/routes/events/features/GameEventCard/styles.css.ts
app/routes/events/features/GameEventSection/GameEventSection.stories.ts
app/routes/events/features/GameEventSection/GameEventSection.tsx
app/routes/events/features/GameEventSection/index.ts
app/routes/events/features/GameEventSection/styles.css.ts
app/routes/events/features/LiveEventSection/LiveEventSection.stories.ts
app/routes/events/features/LiveEventSection/LiveEventSection.tsx
app/routes/events/features/LiveEventSection/index.ts
app/routes/events/features/LiveEventSection/styles.css.ts
app/routes/events/features/StageEventSection/StageEventSection.stories.ts
app/routes/events/features/StageEventSection/StageEventSection.tsx
app/routes/events/features/StageEventSection/index.ts
app/routes/events/features/StageEventSection/styles.css.ts
app/routes/events/handlers/index.ts
app/routes/events/handlers/loader.ts
app/routes/events/route.tsx
app/routes/events/styles.css.ts
app/styles/media.css.ts

feat: impl events page

---

app/routes/_index/features/DetailCard/DetailCard.stories.ts
app/routes/_index/features/DetailCard/DetailCard.tsx
app/routes/_index/features/DetailCard/index.ts
app/routes/_index/features/DetailCard/styles.css.ts
app/routes/_index/features/OverviewSection/OverviewSection.tsx

feat: add stundent counseling with DetailCard

---

public/_routes.json

This reverts commit 555a36bf58b01ea08d13f595276a74ca8da60113.

Revert "fix: update _routes.json (#344)"

---

app/routes/_index/features/EventCard/styles.css.ts

fix: 🐞 remove EventCard footer horizontal padding

---

app/routes/events/features/LiveEventCard/LiveEventCard.tsx

refactor: s/`メインステージ`/`ライブステージ`

---

app/root.tsx

feat: use web fonts for base

---

content-collections.ts

close #429
コンテキスト: https://snct2024.slack.com/archives/C068BMRRW1Y/p1729137019674739
`.gitkeep`は入稿時に削除予定

feat: add schema of sponsor

---

.storybook/preview-head.html
app/routes/_index/features/SponsorCard/SponsorCard.stories.tsx
app/routes/_index/features/SponsorCard/SponsorCard.tsx
app/routes/_index/features/SponsorCard/index.ts
app/routes/_index/features/SponsorCard/styles.css.ts

feat: implement SponsorCard component

---

content-collections.ts

close #442
`team`には、募集時の制約が緩かったのか作品名が入っていたりするので注意...

feat: add schema of departmentExhibition

---

app/routes/_index/features/SponsorCard/styles.css.ts
app/routes/_index/features/SponsorSection/SponsorSection.stories.ts
app/routes/_index/features/SponsorSection/SponsorSection.tsx
app/routes/_index/features/SponsorSection/index.ts
app/routes/_index/features/SponsorSection/styles.css.ts

feat: implement SponsorSection

---

content-collections.ts

feat: add schema of bazar

---

app/routes/bazar/features/ExhibitionCard/ExhibitionCard.stories.ts
app/routes/bazar/features/ExhibitionCard/ExhibitionCard.tsx
app/routes/bazar/features/ExhibitionCard/index.ts
app/routes/bazar/features/ExhibitionCard/styles.css.ts
app/routes/bazar/route.tsx
tests/bazar.test.ts

feat: 🚀 学科展示カードの作成

---

app/routes/events/route.tsx
app/routes/events/styles.css.ts
app/routes/top/features/HeroSection/HeroSection.tsx

feat: 🚀 add Header in event page

---

app/routes/top/features/OverviewSection/styles.css.ts

feat: 🚀 add max width at event section in OverviewSection

---

app/routes/events/features/GhostHouseSection/GhostHouseSection.tsx

fix: rewrite ghost house location
